### ISSUE TITLE
💡 define 'KIRA' as a Composable DePIN

### ISSUE THREAD

**Issue by bt0mx** [KiraCore/docs.kira.network#53]
### Issue page path (local)

introduction.mdx

### Issue page path (docs.kira.network branch)

/docs/

### Description

Why not define 'KIRA' as a Composable DePIN?

**Comment by kmlbgn** [comment]
You're absolutely right! 
We decided to zoom in on certain areas, to keep things less abstract. 
KIRA brings a lot of things on the table at once, we can tag a lot of category, but it would be confusing many.
